language: python

python:
  - '2.6'
  - '2.7'
  - '3.2'
  - '3.3'

env:
  global:
    - secure: GMUWLBrNBeYmVLr+KBXnFhKGb3RLrY6qgApQ9JgMiNBTlmcgVq5tpUYSpQpQTHXVmnU0Xho/NpWo27+ud2QJqXEtgp9q/ZGxrEJsX3SAtUBONphMSjEbaHiH90MgMmgS2wtyxuptKoL66vJ3SLtbTgcMWmEvyMbN0n+f/qIRtlk=

install:
  - python setup.py install

script:
  - python setup.py nosetests

after_success:
  - coveralls
